# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agar_id_int', models.IntegerField()),
                ('agar_name_text', models.CharField(max_length=100)),
                ('agar_temp_text', models.CharField(max_length=20)),
                ('agar_ctx_bool', models.BooleanField()),
            ],
        ),
    ]
