# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 02:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agar',
            old_name='agar_ctx_bool',
            new_name='agar_ctx',
        ),
        migrations.RenameField(
            model_name='agar',
            old_name='agar_id_int',
            new_name='agar_id',
        ),
        migrations.RenameField(
            model_name='agar',
            old_name='agar_name_text',
            new_name='agar_name',
        ),
        migrations.RenameField(
            model_name='agar',
            old_name='agar_temp_text',
            new_name='agar_temp',
        ),
    ]
