# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20171031_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agar',
            name='id',
        ),
        migrations.AlterField(
            model_name='agar',
            name='agar_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
