# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 02:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20171031_0253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agar',
        ),
    ]
