# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '0004_delete_agar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agar_name', models.CharField(max_length=100)),
                ('agar_temp', models.CharField(max_length=20)),
                ('agar_ctx', models.BooleanField()),
            ],
        ),
    ]
