# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 03:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_agar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agar',
            old_name='agar_ctx',
            new_name='ctx',
        ),
        migrations.RenameField(
            model_name='agar',
            old_name='agar_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='agar',
            old_name='agar_temp',
            new_name='temp',
        ),
    ]
