# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('run_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('conditions', models.TextField()),
                ('initials', models.CharField(max_length=20)),
                ('swabber', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Agar',
        ),
        migrations.DeleteModel(
            name='Site',
        ),
    ]
