# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 04:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_agar_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='swabber',
        ),
    ]
