# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_remove_run_swabber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Swabber',
            fields=[
                ('run_id', models.IntegerField(primary_key=True, serialize=False)),
                ('swabber', models.CharField(max_length=20)),
            ],
        ),
    ]
