# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 04:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_swabber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('plate_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cfu', models.IntegerField()),
                ('agar_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Agar')),
                ('run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Run')),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Site')),
            ],
        ),
        migrations.AlterField(
            model_name='swabber',
            name='run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='database.Run'),
        ),
    ]
