# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_auto_20171030_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Isolate',
            fields=[
                ('iso_id', models.IntegerField(primary_key=True, serialize=False)),
                ('plate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Plate')),
            ],
        ),
    ]
