# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 05:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_isolate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isolate',
            name='plate_id',
            field=models.ForeignKey(db_column='plate_id', on_delete=django.db.models.deletion.CASCADE, to='database.Plate'),
        ),
        migrations.AlterField(
            model_name='plate',
            name='agar_id',
            field=models.ForeignKey(db_column='agar_id', on_delete=django.db.models.deletion.CASCADE, to='database.Agar'),
        ),
        migrations.AlterField(
            model_name='plate',
            name='run_id',
            field=models.ForeignKey(db_column='run_id', on_delete=django.db.models.deletion.CASCADE, to='database.Run'),
        ),
        migrations.AlterField(
            model_name='plate',
            name='site_id',
            field=models.ForeignKey(db_column='site_id', on_delete=django.db.models.deletion.CASCADE, to='database.Site'),
        ),
        migrations.AlterField(
            model_name='swabber',
            name='run_id',
            field=models.ForeignKey(db_column='run_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='database.Run'),
        ),
    ]
