# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_agar1log_agar2log_agar3log_agar4log_agar5log_agar6log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agar6log',
            name='id',
        ),
        migrations.AlterField(
            model_name='agar6log',
            name='run_id',
            field=models.ForeignKey(db_column='run_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='database.Run'),
        ),
    ]
