# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_auto_20171102_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agar1log',
            name='id',
        ),
        migrations.RemoveField(
            model_name='agar2log',
            name='id',
        ),
        migrations.RemoveField(
            model_name='agar3log',
            name='id',
        ),
        migrations.RemoveField(
            model_name='agar4log',
            name='id',
        ),
        migrations.RemoveField(
            model_name='agar5log',
            name='id',
        ),
        migrations.AlterField(
            model_name='agar1log',
            name='run_id',
            field=models.ForeignKey(db_column='run_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='database.Run'),
        ),
        migrations.AlterField(
            model_name='agar2log',
            name='run_id',
            field=models.ForeignKey(db_column='run_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='database.Run'),
        ),
        migrations.AlterField(
            model_name='agar3log',
            name='run_id',
            field=models.ForeignKey(db_column='run_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='database.Run'),
        ),
        migrations.AlterField(
            model_name='agar4log',
            name='run_id',
            field=models.ForeignKey(db_column='run_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='database.Run'),
        ),
        migrations.AlterField(
            model_name='agar5log',
            name='run_id',
            field=models.ForeignKey(db_column='run_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='database.Run'),
        ),
    ]
