# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_auto_20171102_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='conditions',
            field=models.TextField(default=''),
        ),
    ]
