# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-05 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_auto_20171102_1946'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agar',
            table='agar',
        ),
    ]
