# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-06 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryDropdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(choices=[('1', 'Relative Abundance/Resistance of Plated Samples'), ('2', 'Other')], default='2', max_length=200)),
            ],
        ),
    ]
